name: 'Wait for github status'
description: 'Wait for a specific github status check to complete'
inputs:
  context:  # id of input
    description: 'Wait for status with context containg this string'
    required: true
    default: 'circleci'
  token:
    description: "Github repo token"
    required: true
outputs:
  status: # id of output
    description: 'Status we waited for, either success, failure, or error'
runs:
  using: 'node20'
  main: 'dist/index.js'
