# Dummy circleci config that sets a status check
# So we can test the github action easily

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/app
    steps:
      - run:
          name: Wait 5 seconds
          command: sleep 5
workflows:
  version: 2
  'Test Suite':
    jobs:
      - build
