on: [push]

jobs:
  wait_for_status:
    runs-on: ubuntu-latest
    name: wait for CircleCI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # To use this repository's private action, you must check out the repository
      - name: Wait for circleci
        uses: ./ # Uses an action in the root directory
        id: wait_for_status
        with:
          context: 'circleci'
          token: ${{ secrets.GITHUB_TOKEN }}

      # Use the output from the `hello` step
      - name: Output the finished status
        run: echo "The status was ${{ steps.wait_for_status.outputs.status }}"
